---
- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: localhost
  become: true
  gather_facts: false
  tags:
    - application_servers
    - flask
  tasks:

  - name: Manage OpenStack InMemory Inventory
    os_server_info:
      cloud: "{{ openstack_cloud | default('openstack') }}"
      region_name: "{{ openstack_region | default('regionOne') }}"
    register: r_instances
  
  - name: Create in-memory Ansible inventory
    add_host:
      group:
        - "{{ item.metadata.group }}"
        - "{{ item['metadata'][' deployment_name'] }}"
      name: "{{ item.public_v4 }}"
    loop: "{{ r_instances.openstack_servers }}"
  
  - name: display inv
    debug:
      var: r_instances

