- import_playbook: in_memory_inventory.yml
- import_playbook: gather_facts.yml
- import_playbook: provision_database_tier.yml
- import_playbook: provision_app_tier.yml
- import_playbook: provision_load_balancer_tier.yml
- import_playbook: smoke_test.yml

