---
- name: End to end smoke tests
  hosts: app_servers:database_servers
  gather_facts: true
  become: true
  tags:
    - smoketest  

  tasks:

    - name: Smoketest Postgres database
      vars:
        #ansible_python_interpreter: /does/not/exist
        ansible_python_interpreter: /opt/virtual_envs/resource_hub/bin/python
      postgresql_ping:
        db: flask_db
        login_host: "{{ groups.database_servers[0] }}"
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      delegate_to: "{{ groups.app_servers[0] }}"
      run_once: true
      tags:
        - smoketest

- name: End to end smoke tests
  hosts: app_servers
  become: false
  gather_facts: false
  tags:
    - smoketest  
  tasks:
 
    - name: Check webserver for correct response
      vars: 
        frontend: "{{ groups.load_balancers[0] }}"
      uri:
        url: "http://{{ frontend }}/ping"
        return_content: yes
      until: '"alive" in result.content'
      retries: 2
      delay: 1
      register: result
      delegate_to: localhost
